import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/header/Header";
import { Nav } from "../components/nav/Nav";
import { Movies } from "../components/movies/Movies";
import { GetServerSideProps } from "next";
import { requests } from "../utils/requests";
import { Movie } from "../types/movie";

interface IHomePageProps {
  movies: Movie[];
}

const Home: NextPage<IHomePageProps> = ({movies}) => {
  return (
    <div>
      {/*
        //* Head section is for metadata of the application
      */}
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Movies movies={movies}/>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const genre = context.query.genre as string;
  const url = `https://api.themoviedb.org/3${
    requests[genre]?.url || requests.fetchTrending.url
  }`;

  const response = await fetch(url);
  const data = await response.json()
  return {
    props: {
      movies : data.results
    }
  }
};
export default Home;
